#!/usr/bin/env python3
"""Compute WCAG contrast ratios for the UrukOS palette and write docs/contrast-report.md."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE_PATH = ROOT / "brand" / "palette.json"
OUT_PATH = ROOT / "docs" / "contrast-report.md"

PAIRS = [
    ("fg", "bg", "body text on primary background"),
    ("fg", "surface", "body text on panels/terminals"),
    ("accent", "bg", "Uruk Amber on background"),
    ("accent", "surface", "Uruk Amber on surface"),
    ("accent2", "surface", "Gilgamesh Bronze on surface (borders/icons only)"),
    ("accent2", "bg", "Gilgamesh Bronze on background (borders/icons only)"),
]


def rel_luminance(rgb: list) -> float:
    def chan(c: int) -> float:
        s = c / 255
        return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4

    r, g, b = (chan(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(rgb1: list, rgb2: list) -> float:
    l1, l2 = rel_luminance(rgb1), rel_luminance(rgb2)
    lo, hi = min(l1, l2), max(l1, l2)
    return (hi + 0.05) / (lo + 0.05)


def main() -> int:
    p = json.loads(PALETTE_PATH.read_text(encoding="utf-8"))
    colors = p["colors"]
    lines = [
        "# Contrast report",
        "",
        "Generated by `tools/contrast-report.py`. Do not hand-edit.",
        "",
        "| Foreground | Background | Ratio | Use |",
        "|---|---|---|---|",
    ]
    for fg_key, bg_key, use in PAIRS:
        ratio = contrast(colors[fg_key]["rgb"], colors[bg_key]["rgb"])
        lines.append(
            f"| {colors[fg_key]['name']} `{colors[fg_key]['hex']}` | "
            f"{colors[bg_key]['name']} `{colors[bg_key]['hex']}` | "
            f"{ratio:.2f}:1 | {use} |"
        )
    lines += [
        "",
        "Rules: Clay Tablet must stay high-contrast on bg and surface. Uruk Amber is safe for text and highlights. Gilgamesh Bronze is ~3.5:1: use for borders and icons, never body text.",
    ]
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
    print("\n".join(lines[6:]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
