#!/usr/bin/env python3
"""Generate every UrukOS theme file from brand/palette.json.

Usage:
    python3 tools/gen-palette.py          regenerate all theme files
    python3 tools/gen-palette.py --check  verify files are in sync (exit 1 if not)

Never hand-edit a theme file; edit brand/palette.json and re-run this script.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE_PATH = ROOT / "brand" / "palette.json"


def load_palette() -> dict:
    with PALETTE_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def C(p: dict, key: str) -> str:
    return p["colors"][key]["hex"]


def ANSI(p: dict) -> dict:
    a = p["ansi"]
    return {
        "black": a["black"],
        "red": a["red"],
        "green": a["green"],
        "yellow": a["yellow"],
        "blue": a["blue"],
        "magenta": a["magenta"],
        "cyan": a["cyan"],
        "white": a["white"],
        "bright_black": a["bright_black"],
        "bright_red": a["bright_red"],
        "bright_green": a["bright_green"],
        "bright_yellow": a["bright_yellow"],
        "bright_blue": a["bright_blue"],
        "bright_magenta": a["bright_magenta"],
        "bright_cyan": a["bright_cyan"],
        "bright_white": a["bright_white"],
    }


def ghostty_theme(p: dict) -> str:
    a = ANSI(p)
    keys = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    lines = [
        "# UrukOS Ghostty theme - GENERATED by tools/gen-palette.py, do not edit",
        f"background = {C(p, 'bg')}",
        f"foreground = {C(p, 'fg')}",
        f"cursor-color = {C(p, 'accent')}",
        f"selection-background = {C(p, 'accent2')}",
        f"selection-foreground = {C(p, 'fg')}",
    ]
    for i, k in enumerate(keys):
        lines.append(f"palette = {i}={a[k]}")
    for i, k in enumerate(keys):
        lines.append(f"palette = {i + 8}={a['bright_' + k]}")
    return "\n".join(lines) + "\n"


def fish_theme(p: dict) -> str:
    a = ANSI(p)
    lines = [
        "# UrukOS fish theme - GENERATED by tools/gen-palette.py, do not edit",
        f"set -g fish_color_normal {a['white'].lstrip('#')}",
        f"set -g fish_color_command {C(p, 'accent').lstrip('#')}",
        f"set -g fish_color_keyword {a['magenta'].lstrip('#')}",
        f"set -g fish_color_param {a['cyan'].lstrip('#')}",
        f"set -g fish_color_quote {a['green'].lstrip('#')}",
        f"set -g fish_color_redirection {a['yellow'].lstrip('#')}",
        f"set -g fish_color_end {a['bright_blue'].lstrip('#')}",
        f"set -g fish_color_error {a['red'].lstrip('#')}",
        f"set -g fish_color_comment {a['bright_black'].lstrip('#')}",
        f"set -g fish_color_selection --background={C(p, 'accent2').lstrip('#')}",
        f"set -g fish_color_search_match --background={C(p, 'accent').lstrip('#')}",
        f"set -g fish_color_cwd {C(p, 'accent').lstrip('#')}",
        f"set -g fish_pager_color_completion {C(p, 'fg').lstrip('#')}",
        f"set -g fish_pager_color_selected_background --background={C(p, 'accent2').lstrip('#')}",
    ]
    return "\n".join(lines) + "\n"


def tmux_conf(p: dict) -> str:
    return (
        "# UrukOS tmux colors - GENERATED by tools/gen-palette.py, do not edit\n"
        f"set -g status-style 'fg={C(p, 'fg')},bg={C(p, 'surface')}'\n"
        f"set -g status-left '#[fg={C(p, 'bg')},bg={C(p, 'accent')},bold] UrukOS #[default] '\n"
        f"set -g status-right '#[fg={C(p, 'fg')}] %H:%M #[fg={C(p, 'bg')},bg={C(p, 'accent2')}] #h '\n"
        f"set -g window-status-style 'fg={C(p, 'fg')},bg={C(p, 'surface')}'\n"
        f"set -g window-status-current-style 'fg={C(p, 'bg')},bg={C(p, 'accent')},bold'\n"
        f"set -g pane-border-style 'fg={C(p, 'accent2')}'\n"
        f"set -g pane-active-border-style 'fg={C(p, 'accent')}'\n"
        f"set -g message-style 'fg={C(p, 'bg')},bg={C(p, 'accent')}'\n"
    )


def bat_theme(p: dict) -> str:
    a = ANSI(p)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- UrukOS bat theme - GENERATED by tools/gen-palette.py, do not edit -->
<plist version="1.0">
<dict>
  <key>name</key><string>UrukOS</string>
  <key>settings</key>
  <array>
    <dict><key>settings</key><dict><key>foreground</key><string>{C(p, "fg")}</string><key>background</key><string>{C(p, "bg")}</string></dict></dict>
    <dict><key>name</key><string>Comment</string><key>settings</key><dict><key>foreground</key><string>{a["bright_black"]}</string></dict></dict>
    <dict><key>name</key><string>Keyword</string><key>settings</key><dict><key>foreground</key><string>{a["magenta"]}</string><key>fontStyle</key><string>bold</string></dict></dict>
    <dict><key>name</key><string>String</string><key>settings</key><dict><key>foreground</key><string>{a["green"]}</string></dict></dict>
    <dict><key>name</key><string>Constant</string><key>settings</key><dict><key>foreground</key><string>{a["yellow"]}</string></dict></dict>
    <dict><key>name</key><string>Entity</string><key>settings</key><dict><key>foreground</key><string>{a["cyan"]}</string></dict></dict>
    <dict><key>name</key><string>Support</string><key>settings</key><dict><key>foreground</key><string>{a["blue"]}</string></dict></dict>
    <dict><key>name</key><string>Function</string><key>settings</key><dict><key>foreground</key><string>{C(p, "accent")}</string></dict></dict>
    <dict><key>name</key><string>Error</string><key>settings</key><dict><key>foreground</key><string>{a["red"]}</string></dict></dict>
  </array>
</dict>
</plist>
"""


def eza_theme(p: dict) -> str:
    a = ANSI(p)
    return (
        "# UrukOS eza theme - GENERATED by tools/gen-palette.py, do not edit\n"
        f'directory: "{C(p, "accent")}"\n'
        f'executable: "{a["green"]}"\n'
        f'symlink: "{a["cyan"]}"\n'
        f'read: "{C(p, "fg")}"\n'
        f'write: "{a["yellow"]}"\n'
        f'execute: "{a["red"]}"\n'
        f'media: "{a["magenta"]}"\n'
        f'archive: "{a["bright_yellow"]}"\n'
        f'date: "{a["bright_black"]}"\n'
        f'size: "{a["blue"]}"\n'
        f'user: "{C(p, "accent2")}"\n'
    )


def fastfetch_config(p: dict) -> str:
    return """// UrukOS fastfetch config - GENERATED by tools/gen-palette.py, do not edit
{
  "$schema": "https://fastfetch.dev/schema.json",
  "logo": {
    "type": "file",
    "source": "/usr/share/urukos/fastfetch-logo.txt",
    "color": { "1": "yellow" }
  },
  "display": { "separator": "  " },
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "de",
    "wm",
    "terminal",
    "cpu",
    "gpu",
    "memory",
    "disk",
    { "type": "colors", "symbol": "circle" }
  ]
}
"""


def kde_colors(p: dict) -> str:
    bg, surface, accent, accent2, fg = (
        C(p, k) for k in ("bg", "surface", "accent", "accent2", "fg")
    )

    def triple(hexv: str) -> str:
        h = hexv.lstrip("#")
        return f"{int(h[0:2], 16)},{int(h[2:4], 16)},{int(h[4:6], 16)}"

    return f"""[ColorEffects:Disabled]
ChangeSelectionColor=true
Color={triple(surface)}
ColorAmount=0.025

[Colors:Button]
BackgroundAlternate={triple(surface)}
BackgroundNormal={triple(surface)}
DecorationFocus={triple(accent)}
DecorationHover={triple(accent2)}
ForegroundActive={triple(accent)}
ForegroundLink={triple(accent)}
ForegroundNormal={triple(fg)}
ForegroundPositive={triple(accent)}
ForegroundVisited={triple(accent2)}

[Colors:Selection]
BackgroundAlternate={triple(accent2)}
BackgroundNormal={triple(accent)}
DecorationFocus={triple(accent)}
DecorationHover={triple(accent)}
ForegroundActive={triple(fg)}
ForegroundLink={triple(fg)}
ForegroundNormal={triple(bg)}
ForegroundPositive={triple(bg)}
ForegroundVisited={triple(bg)}

[Colors:Tooltip]
BackgroundAlternate={triple(surface)}
BackgroundNormal={triple(surface)}
DecorationFocus={triple(accent)}
DecorationHover={triple(accent)}
ForegroundActive={triple(fg)}
ForegroundLink={triple(accent)}
ForegroundNormal={triple(fg)}
ForegroundPositive={triple(accent)}
ForegroundVisited={triple(accent2)}

[Colors:View]
BackgroundAlternate={triple(surface)}
BackgroundNormal={triple(bg)}
DecorationFocus={triple(accent)}
DecorationHover={triple(accent2)}
ForegroundActive={triple(accent)}
ForegroundLink={triple(accent)}
ForegroundNormal={triple(fg)}
ForegroundPositive={triple(accent)}
ForegroundVisited={triple(accent2)}

[Colors:Window]
BackgroundAlternate={triple(surface)}
BackgroundNormal={triple(surface)}
DecorationFocus={triple(accent)}
DecorationHover={triple(accent2)}
ForegroundActive={triple(accent)}
ForegroundLink={triple(accent)}
ForegroundNormal={triple(fg)}
ForegroundPositive={triple(accent)}
ForegroundVisited={triple(accent2)}

[General]
ColorScheme=UrukOS
Name=UrukOS
shadeSortColumn=true
"""


def kde_defaults(p: dict) -> str:
    return """[General]
ColorScheme=UrukOS

[Icons]
Theme=breeze-dark

[KDE]
LookAndFeelPackage=org.urukos.desktop
"""


def plymouth_script(p: dict) -> str:
    def f(key: str) -> tuple:
        h = C(p, key).lstrip("#")
        return (int(h[0:2], 16) / 255, int(h[2:4], 16) / 255, int(h[4:6], 16) / 255)

    bg = f("bg")
    surface = f("surface")
    return f"""// UrukOS Plymouth script - GENERATED by tools/gen-palette.py, do not edit
Window.SetBackgroundTopColor({bg[0]:.3f}, {bg[1]:.3f}, {bg[2]:.3f});
Window.SetBackgroundBottomColor({surface[0]:.3f}, {surface[1]:.3f}, {surface[2]:.3f});

logo.image = Image("watermark.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 40);

message_sprite = Sprite();

fun refresh_callback () {{
    if (progress_bar) {{
        progress_bar.sprite.SetX(Window.GetWidth() / 2 - progress_bar.image.GetWidth() / 2);
    }}
}}
Plymouth.SetRefreshFunction(refresh_callback);

fun message_callback (text) {{
    my_image = Image.Text(text, 0.99, 0.95, 0.90);
    message_sprite.SetImage(my_image);
    message_sprite.SetX(Window.GetWidth() / 2 - my_image.GetWidth() / 2);
    message_sprite.SetY(Window.GetHeight() / 2 + 80);
}}
Plymouth.SetMessageFunction(message_callback);
"""


TEMPLATES = {
    "terminal/ghostty/urukos": ghostty_theme,
    "terminal/fish/urukos.theme": fish_theme,
    "terminal/tmux/urukos.conf": tmux_conf,
    "terminal/bat/themes/urukos.tmTheme": bat_theme,
    "terminal/eza/theme.yml": eza_theme,
    "terminal/fastfetch/config.jsonc": fastfetch_config,
    "kde/colors/UrukOS.colors": kde_colors,
    "kde/look-and-feel/org.urukos.desktop/contents/defaults": kde_defaults,
    "plymouth/urukos/urukos.script": plymouth_script,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true", help="verify generated files are in sync"
    )
    args = ap.parse_args()

    palette = load_palette()
    stale = []
    for rel, fn in TEMPLATES.items():
        expected = fn(palette)
        path = ROOT / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(f"wrote {rel}")
    if args.check:
        if stale:
            print("STALE: " + ", ".join(stale))
            return 1
        print("OK: all theme files in sync with brand/palette.json")
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
